# Generated by Django 6.0 on 2025-12-08 21:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "detailed_description",
                    models.TextField(blank=True, verbose_name="Подробное описание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATURE", "Природный объект"),
                            ("CULTURE", "Культурный объект"),
                            ("MUSEUM", "Музей"),
                            ("GUESTHOUSE", "Гостевой дом / база"),
                            ("SHAMAN_CLINIC", "Шаманская клиника"),
                            ("FOOD", "Кафе / ресторан"),
                            ("OTHER", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Регион / район"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес / точка въезда"
                    ),
                ),
                (
                    "access_info",
                    models.TextField(blank=True, verbose_name="Как добраться / дорога"),
                ),
                (
                    "visit_duration_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        max_digits=4,
                        verbose_name="Время на посещение (часы)",
                    ),
                ),
                (
                    "physical_level",
                    models.CharField(
                        choices=[
                            ("EASY", "Лёгкий"),
                            ("MEDIUM", "Средний"),
                            ("HARD", "Сложный"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Физическая сложность",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("YEAR_ROUND", "Круглый год"),
                            ("SPRING", "Весна"),
                            ("SUMMER", "Лето"),
                            ("AUTUMN", "Осень"),
                            ("WINTER", "Зима"),
                        ],
                        default="YEAR_ROUND",
                        max_length=20,
                        verbose_name="Сезон доступности",
                    ),
                ),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Низкий"),
                            ("MEDIUM", "Средний"),
                            ("HIGH", "Высокий"),
                        ],
                        max_length=20,
                        verbose_name="Уровень цен",
                    ),
                ),
                (
                    "base_cost",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ориентировочная стоимость (₽)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="Ссылка на фотографию"),
                ),
                (
                    "avg_rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Средний рейтинг"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Объект (POI)",
                "verbose_name_plural": "Объекты (POI)",
            },
        ),
        migrations.CreateModel(
            name="PoiPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="Ссылка на фото")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tours.poi",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото объекта",
                "verbose_name_plural": "Фотографии объектов",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка (1–5)",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст отзыва")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tours.poi",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название маршрута"),
                ),
                (
                    "days_count",
                    models.PositiveIntegerField(default=1, verbose_name="Кол-во дней"),
                ),
                (
                    "total_duration_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Общее время (часы)"
                    ),
                ),
                (
                    "total_cost",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ориентировочная стоимость (₽)",
                    ),
                ),
                (
                    "equipment",
                    models.TextField(blank=True, verbose_name="Необходимая экипировка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(default=1, verbose_name="День"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Порядок в дне"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "visit_time_estimate",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        max_digits=4,
                        verbose_name="Планируемое время (часы)",
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours.poi",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="tours.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка маршрута",
                "verbose_name_plural": "Точки маршрута",
                "ordering": ["day_number", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "travel_style",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активный"),
                            ("CULTURAL", "Культурно-познавательный"),
                            ("RELAX", "Релакс / отдых"),
                            ("MIXED", "Смешанный"),
                        ],
                        default="MIXED",
                        max_length=20,
                        verbose_name="Стиль путешествия",
                    ),
                ),
                (
                    "budget_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Низкий"),
                            ("MEDIUM", "Средний"),
                            ("HIGH", "Высокий"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Уровень бюджета",
                    ),
                ),
                (
                    "physical_level",
                    models.CharField(
                        choices=[
                            ("EASY", "Лёгкий"),
                            ("MEDIUM", "Средний"),
                            ("HARD", "Сложный"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Физподготовка",
                    ),
                ),
                (
                    "preferred_season",
                    models.CharField(
                        choices=[
                            ("YEAR_ROUND", "Круглый год"),
                            ("SPRING", "Весна"),
                            ("SUMMER", "Лето"),
                            ("AUTUMN", "Осень"),
                            ("WINTER", "Зима"),
                        ],
                        default="SUMMER",
                        max_length=20,
                        verbose_name="Предпочитаемый сезон",
                    ),
                ),
                (
                    "with_children",
                    models.BooleanField(default=False, verbose_name="С детьми"),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True, verbose_name="Интересы (шаманизм, археология...)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Особые пожелания / ограничения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
