# Generated by Django 6.0 on 2025-12-16 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_review_uniq_review_user_poi"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="is_shared",
            field=models.BooleanField(default=False, verbose_name="Доступ по ссылке"),
        ),
        migrations.AddField(
            model_name="route",
            name="share_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Токен для ссылки",
            ),
        ),
    ]
