# Generated by Django 6.0 on 2025-12-16 07:29

from django.db import migrations
import uuid

def fill_uuid(apps, schema_editor):
    Route = apps.get_model("tours", "Route")
    for r in Route.objects.filter(share_uuid__isnull=True).only("id"):
        r.share_uuid = uuid.uuid4()
        r.save(update_fields=["share_uuid"])

class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0003_route_is_shared_route_share_uuid"),  # тут твоя предыдущая миграция
    ]

    operations = [
        migrations.RunPython(fill_uuid, migrations.RunPython.noop),
    ]
