# Generated by Django 6.0 on 2025-12-16 07:32

import uuid
from django.db import migrations, models
from django.db.models import Count


def fix_share_uuid_duplicates(apps, schema_editor):
    Route = apps.get_model("tours", "Route")

    for r in Route.objects.filter(share_uuid__isnull=True).only("id"):
        r.share_uuid = uuid.uuid4()
        r.save(update_fields=["share_uuid"])

    dupes = (
        Route.objects
        .values("share_uuid")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )

    for d in dupes:
        same = list(
            Route.objects
            .filter(share_uuid=d["share_uuid"])
            .order_by("id")
            .only("id")
        )
        for r in same[1:]:
            r.share_uuid = uuid.uuid4()
            r.save(update_fields=["share_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_fill_route_share_uuid"),
    ]

    operations = [
        migrations.RunPython(fix_share_uuid_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="route",
            name="share_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Токен для ссылки",
            ),
        ),
    ]
